export const ROUTES = {
    DASHBOARD: "/",
    PROFILES: "user/profile",
    LOGIN: "/login",
    ORDERS: "user/order",
    PRODUCTS: "/products",
    USERS: "/users",
    SETTINGS: "/settings",
    CATEGORIES: "/categories",
    LOGOUT: "/login",
    ADMIN_DASHBOARD: "/admin",
    SHIPPER_DASHBOARD: "/admin/shipper",

    ADMIN_PRODUCT: "/admin/product",
    SELLER_PRODUCT: "/seller/product",
    SELLER_ORDER: "/seller/order",

    ADMIN_CUSTOMER: "/admin/customer",
    ADMIN_STAFF: "/admin/staff",
    ADMIN_SELLER: "/admin/seller",
    ADMIN_CATEGORY: "/admin/category",
    ADMIN_BRAND: "/admin/brand",
    ADMIN_ORDER: "/admin/order",
    ADMIN_POSTER: "/admin/poster",
    ADMIN_IMPORT: "/admin/receipt",
    ADMIN_PURCHASE: "/admin/purchase",
    ADMIN_EXPORT: "/admin/export",
    ADMIN_PROMOTION: "/admin/promotion",
    ADMIN_SHIPPING: "/admin/shipping",
    ADMIN_SUPPLIER: "/admin/supplier",
    ADMIN_INVENTORY: "/admin/inventory",
    SELLER_VERIFY: "/seller/verify",
    SELLER_DASHBOARD: "/seller",
    SELLER_LOGIN: "/seller/login",
    VERIFY_FORGOT: "/forgot_password/verify",
    CONFIRM_FORGOT: "/forgot_password/confirm",

  };
  