export const API_ENDPOINTS = {
    ORDERS: "order",
    RETRY_PAYMENT_ORDER: "paypal/payment/retry",
    CANCEL_ORDER: "order/request-cancel",
    GET_ORDERS:"order/get",
    ORDER_DETAIL: "order/detail",
    REVIEW_ADD: "review/add",
    REVIEW_UPDATE: "review/update",
    REVIEW_DETAIL_BY_PRODUCT_ID:"review/detail/product",
    USERS: "users",
    CHECKOUT: "paypal/payment",
    REGISTER: "auth/signup",
    PRODUCTS: "product",
    PRODUCT_DETAIL: "product/detail",
    PRODUCTS_SEARCH: "product/search",
    PRODUCT_GET_MAX_PRICE: "product/getMaxPrice",
    PRODUCTS_BEST_SELL: "product/best-sell",
    PRODUCTS_NEW: "product/new",
    PRODUCTS_PROMOTION: "product/promotion",
    PAYPAL_EXECUTE: "paypal/payment/execute",

    PROVINCE: "/p",
    DISTRICT: "/d",
    WARD: "/w",


    PRODUCT_DELETE: "admin/product/delete",
    PRODUCT_APPROVE: "admin/product/approve",
    PRODUCTS_ADMIN: "admin/product",
    PRODUCT_ADD_ADMIN: "admin/product/add",
    PRODUCT_UPDATE_ADMIN: "admin/product/update",
    ROLES: "admin/role",
    IMAGE_ADMIN: "image/add",
    USERS_ADMIN: "admin/user",
    CUSTOMERS_ADMIN: "admin/customer",
    CUSTOMERS_DELETE: "admin/customer/delete",
    CUSTOMERS_APPROVE: "admin/customer/approve",

    STAFFS_ADMIN: "admin/staff",
    STAFFS_DELETE: "admin/staff/delete",
    STAFFS_APPROVE: "admin/staff/approve",

    USER_DELETE: "admin/user/delete",
    USER_APPROVE: "admin/user/approve",
    USER_ADD_ADMIN: "admin/user/add",
    USER_UPDATE_ADMIN: "admin/user/update",
    
    CATEGORIES_ADMIN: "admin/category",
    CATEGORY_DELETE: "admin/category/delete",
    CATEGORY_APPROVE: "admin/category/approve",
    CATEGORY_UPDATE_ADMIN: "admin/category/update",
    CATEGORY_ADD_ADMIN: "admin/category/add",

    POSTERS_ADMIN: "admin/poster",
    POSTER_DELETE: "admin/poster/delete",
    POSTER_APPROVE: "admin/poster/approve",
    POSTER_UPDATE_ADMIN: "admin/poster/update",
    POSTER_ADD_ADMIN: "admin/poster/add",

    PROMOTIONS_ADMIN: "admin/promotion",
    PROMOTION_DELETE: "admin/promotion/delete",
    PROMOTION_APPROVE: "admin/promotion/approve",
    PROMOTION_UPDATE_ADMIN: "admin/promotion/update",
    PROMOTION_ADD_ADMIN: "admin/promotion/add",

    BRANDS_ADMIN: "admin/brand",
    BRAND_DELETE: "admin/brand/delete",
    BRAND_APPROVE: "admin/brand/approve",
    BRAND_UPDATE_ADMIN: "admin/brand/update",
    BRAND_ADD_ADMIN: "admin/brand/add",

    PURCHASE_ORDERS_ADMIN: "admin/purchase-order",
    PURCHASE_ORDERS_ACTIVE_ADMIN: "admin/purchase-order/active",
    PURCHASE_ORDER_ADD_ADMIN: "admin/purchase-order/add",

    RECEIPTS_ADMIN: "admin/receipt",
    RECEIPT_ADD_ADMIN: "admin/receipt/add",

    SUPPLIERS_ADMIN: "admin/supplier",
    SUPPLIERS_DELETE: "admin/supplier/delete",
    SUPPLIERS_APPROVE: "admin/supplier/approve",
    SUPPLIERS_UPDATE_ADMIN: "admin/supplier/update",
    SUPPLIERS_ADD_ADMIN: "admin/supplier/add",
    SUPPLIERS_PRODUCT_ADMIN: "admin/supplier/product",
    SUPPLIERS: "supplier",


    REPORT_ANLYTICS: "admin/report/analytics",
    REPORT_SALE_HISTORY: "admin/report/revenue",
    REPORT_SALE_HISTORY_BETWEEN: "admin/report/revenue/between",
    REPORT_PROFIT_BETWEEN: "admin/report/profit/between",

    REPORT_SOLD_BY_CATEGORY: "admin/report/category",
    REPORT_ORDER_OVERVIEW: "admin/report/order",
    REPORT_ORDER_CANCEL_OVERVIEW: "admin/report/order-cancel",
    REPORT_USER_OVERVIEW: "admin/report/user",
    REPORT_REVIEW_OVERVIEW: "admin/report/review",


    ORDERS_ADMIN: "admin/order",
    ORDERS_SHIPPER: "shipper/order",
    INVOICE_ADMIN: "admin/invoice/get",
    INVOICE_UPDATE_ADMIN: "admin/invoice/update",
    INVOICE_ADD_ADMIN: "admin/invoice/add",

    ORDERS_CANCEL_ADMIN: "admin/order/cancel",
    ORDERS_SHIPPER_ADMIN: "admin/order/shipper",
    SHIPPERS: "admin/staff/shipper",
    ORDERS_CANCEL_SHIPPER: "shipper/order/cancel",
    ORDERS_DONE_SHIPPER: "shipper/order/done",

    CATEGORIES: "category",
    BRANDS: "brand",
    CARTS: "cart",
    CART_ADD: "cart/add",
    GET_ADDRESS: "address/get",
    GET_ADDRESS_DEFAULT: "address/default",
    ADDRESS_PROVINCE: "address/province",
    ADDRESS_DISTRICT: "address/district",
    ADDRESS_WARD: "address/ward",
    ADDRESS: "address",
    ADDRESS_UPDATE: "address/update",
    ADDRESS_ADD: "address/add",
    ADDRESS_DELETE: "address/delete",
    ME: "profile",
    ME_ADMIN: "admin/profile",
    PROFILE_AVATAR: "profile/avatar",
    PROFILE_NAME: "profile/change",
    ADD_CARTS: "cart/add",
    POSTERS: "poster",
    REVIEWS_BY_PRODUCT: "review/get",
    REVIEWS_BY_USER: "review/user/get",
    PARENT_CATEGORIES: "category",
    PROFILE_UPDATE: "profile-update",
    LOGOUT: "logout",
    LOGIN: "auth/login",
    LOGIN_ADMIN: "auth/login/staff",
    LOGIN_SHIPPER: "auth/login/shipper",
    CHANGE_PASSWORD: "profile/password",
    FORGET_PASSWORD: "forget-password",
    VERIFY_FORGET_PASSWORD_TOKEN: "verify-forget-password-token",
    RESET_PASSWORD: "reset-password",
    DOWNLOAD_INVOICE: "download/invoice",
  };
  